[package]
name = "color-picker"
author = "daru"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
notify-rust = "4.11.0"
wl-clipboard-rs = "0.8.1"
